---

## ☕ Support this project
If TeleManager helped you bypass those annoying account limits, consider buying me a coffee! Your support helps me keep the project updated and free.

[❤️ Sponsor on GitHub](https://github.com/sponsors/Eul45)
